language: python

cache:
        directories:
                - $HOME/.wheelhouse/
env:
        global:
                - TRAVIS_CACHE=$HOME/.travis_cache/
        matrix:
                include:
                        - python: "2.7"
                          env:
                                - TOX_ENV=py27
                        - python: "3.5"
                          env: 
                                  - TOX_ENV=py35
                        - python: "3.6"
                          env:
                                  - TOX_ENV=py36
                        - python: "2.7"
                          env:
                                - TOX_ENV=coverage
install:
          - pip install --upgrade pip
          - pip install -r test_requirements.txt
script: 
        - tox -e $TOX_ENV
