language: python
python:
          - "2.7"
          - "3.5"
          - "3.6"
install:
          - "pip install pytest pytest_mock coveralls six"
          - "pip  install -r requirements.txt"
          - "pip install -r test_requirements.txt"
          - "python setup.py -q install"
script: 
        - pytest --cov atlasclient/

after_success:
        coveralls
