language: python

addons:
        apt:
                packages:
                        - python3.5
                        - python3.6
cache:
        directories:
                - $HOME/.wheelhouse/
env:
        global:
                - TRAVIS_CACHE=$HOME/.travis_cache/
        matrix:
                - TOX_ENV=py27
                - TOX_ENV=py35
                - TOX_ENV=py36
                - TOX_ENV=coverage
install:
          - pip install --upgrade pip
          - pip install -r test_requirements.txt
script: 
        - tox -e $TOX_ENV

after_success:
        coveralls
