language: python
python:
- '3.6'
- '3.7'
cache:
  directories:
  - "$HOME/.wheelhouse/"
env:
  global:
  - TRAVIS_CACHE=$HOME/.travis_cache/
  matrix:
    include:
    - python: '3.6'
      env:
      - TOX_ENV=py36
    - python: '3.7'
      env:
      - TOX_ENV=py36
    - python: '3.6'
      env:
      - TOX_ENV=coverage
install:
- pip install --upgrade pip
- pip install -r test_requirements.txt
script:
- tox -e $TOX_ENV
after_success: coveralls
deploy:
  matrix:
  - provider: pypi
    user: __token__
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      repo: verdan/pyatlasclient
    password:
      secure: bB30t47FNebDERPuFjz4B9PNVeqngKsVPV2HLP/4V7mRK4QK74Nl07uM4zxBFHafGTRsBx73AFo3WJOgW0WOiaEZ7NtJxhP2Vt88pZVh4sQrr9KrGjvAV56Sd72WtMT9J0bngEiLaAoEIGk+FEVrYhThJxREt7aIoWXqUgIsGwLoPZjYQO9p+oqLQk2/fg4Cj5T+mpqtxM1mUy81mTN/HXKGRKgQR6bfVcVlUE6LQ24Ss6QWj6tBxzXy6vGY0LB3nbJlDWzI/VG75zYzFSf9/yrp5PGSwK2+K9g6ZqliiW6UwfZOHmfN4TpIH1Y7pomhhF7yM8zfoGz8SPMpPV+ck5IR0+jFN5PSM5SwRtUwOz722G8XAqtKdlqxiKZZE0JbVHSH9u3rZzQpRCFioOI9bV/tRZX+MHcON1dWdl6eH2x9nmR6iAmcX8kuJrgJSGbSee9m0/n7ZSKrzk2QrKS4lkpddIgw8j/IBVMufFAdG+EOKxGcXUhUToLIVKWdR3HDvD7rh8tQ+YISZ74gpkCjd5jw9QLUGRjxagriG9Ee2ZXLCI6VyiQj0S970ficGMShJqKVjlh0GvjnvGMqKiAgBwgmI/9ncSlS1qIplVjffPAQQTnIPuuoJb/piirev1JSq2Ti9a5ZGVcvAGbqhKvTkrUi08wTzdqn0DCnI+TXDz0=
