language: python
python:
          - "2.7"
          - "3.5"
          - "3.6"
install:
          - "pip install pytest pytest_mock coveralls pep8 six"
script: 
        - pytest
after_success:
        coveralls
