language: python
env:
        matrix:
                - TOX_ENV=py27
                - TOX_ENV=py35
                - TOX_ENV=py36
install:
          - "pip install pytest pytest_mock coveralls six"
          - "pip  install -r requirements.txt"
          - "pip install -r test_requirements.txt"
          - "python setup.py -q install"
script: 
        - tox

after_success:
        coveralls
